language: node_js
node_js:
- '8'
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: alexander.mancevice@gmail.com
  api_key:
    secure: IuOBvmIsmK1IXoTNV8HLoGJfTdMkDk2XPFHnH6fqwKg4UoQ9wlWVuIcSUJgsPdAKNO1nUCRZu7zV3bz6S6jsTCemxYa7+714kXzAW+FZUJ7gYIKYEEA60h6lkZiZqCoxjW5tcRbS/62iAH6XgbqB+A5DQEbpdpOyItG+KIY8ZUAtnT9HO66NFL88G+dHWzm56D+vTqnQYH6HTZRFJFILe8SkcpxqexDfuBrAodEYv/tvXzR71AeSf6POQloARfejIsRLRX76YV/Ezz6luOGZK0ALzgdruMyM+gFF05gOfm9q31EZbYY6erSxXeP4GDOJPZDyIhjfgVVjygJENRkY2mEamrmBNj2+96jI1Ac/QjciqA/BAS5bX8+dEcRv7bxaCEDSrEDvjSc7q7yh/C2Xmbt/ad5Pg99wyvAtAzN4gJeh1CUB5pDEwXGym51tmpsbja9zU3chXNBlt+YVqB8r/N0EoFYhlcbBUf+495UbEoSFs9MzElG7/KqMJ2FJhGjKT1WsespTD6kpRiqbfn+qWJauC9SanOyZtLbpy5czgdTPeVOUVPWsypVr4S0bJKiWTw1LZMkcEstch5bQDhpt9tBcFuUl47TQ8sRdUHnfvPr6PeHidu23sIuN0eQZpLelTVz4EqnCtCRMpaFxufUev0sl5uQrd2PCo2RltVoZ0z0=
  on:
    tags: true
    repo: amancevice/hidden-drive
  skip_cleanup: true
